export const gameModeDataMap = {
    "Maze Duel": {
        id: "maze-duel",
        description: "1v1 battles in a small maze.",
        options: [
            {
                key: "mazeSize",
                label: "Maze Size",
                type: "dropdown",
                values: ["Small", "Medium", "Large"],
                defaultValue: "Medium",
                description: "Determines the overall complexity and area of the maze.",
            },
            {
                key: "playerCount",
                label: "Player Count",
                type: "number",
                values: [],
                min: 2,
                max: 2,
                defaultValue: "2",
                description: "Only 2 players for head-to-head matches.",
            },
            {
                key: "visibility",
                label: "Visibility Range",
                type: "dropdown",
                values: ["Low", "Medium", "High"],
                defaultValue: "High",
                description:
                    "Controls how far players can see in the maze. Higher visibility makes it easier to spot opponents and navigate.",
            },
        ],
    },
    "Maze Royale": {
        id: "maze-royale",
        description: "Up to 10 players battle it out. Last player standing wins.",
        options: [
            {
                key: "mazeSize",
                label: "Maze Size",
                type: "dropdown",
                values: ["Medium", "Large", "Extra Large"],
                defaultValue: "Large",
                description: "Larger mazes support more players and hiding spaces.",
            },
            {
                key: "playerCount",
                label: "Player Count",
                type: "number",
                values: [],
                min: 2,
                max: 10,
                defaultValue: "6",
                description: "Choose player count (2 to 10).",
            },
            {
                key: "decayRate",
                label: "Visibility Decay Rate",
                type: "dropdown",
                values: ["Slow", "Normal", "Fast"],
                defaultValue: "Normal",
                description: "Controls how quickly player visibility fades.",
            },
            {
                key: "allowSpectators",
                label: "Allow Spectators",
                type: "dropdown",
                values: ["Yes", "No"],
                defaultValue: "Yes",
                description: "Choose whether others can watch the match.",
            },
        ],
    },
    "Tag Maze": {
        id: "tag-maze",
        description: "One player is 'It' and must tag others before time runs out.",
        options: [
            {
                key: "mazeSize",
                label: "Maze Size",
                type: "dropdown",
                values: ["Small", "Medium", "Large"],
                defaultValue: "Medium",
                description: "Affects mobility and strategy.",
            },
            {
                key: "playerCount",
                label: "Player Count",
                type: "number",
                values: [],
                min: 2,
                max: 8,
                defaultValue: "4",
                description: "Player count (2 to 8).",
            },
            {
                key: "tagTimer",
                label: "'It' Timer (sec)",
                type: "number",
                values: [],
                min: 30,
                max: 300,
                defaultValue: "120",
                description: "Duration the 'It' player has to tag someone.",
            },
            {
                key: "rotationMode",
                label: "Random 'It' Rotation",
                type: "dropdown",
                values: ["Every Round", "On Timeout", "Never"],
                defaultValue: "Every Round",
                description: "When the 'It' role rotates.",
            },
        ],
    },
};

